### ISSUE TITLE
La validation doit se faire via un robotframework + pymodbus

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/pza-emu-hanmatek-hm310t#3]
Il ne faut pas utiliser panduza dans cette partie

**Comment by XdoctorwhoZ** [comment]
Il faut vérifier que chaque registre répond correctement.

- https://pymodbus.readthedocs.io/en/latest/
- https://github.com/XdoctorwhoZ/robot-framework-template
- https://xdoctorwhoz.github.io/blog/posts/20230211-psu-hm310t/

**Comment by QuentinChopinet** [comment]
Le test psu.robot (dans tests/robot/) valide les fonctionnalités
- Read PSU info
- Enable
- voltage
- Amps max
- Resistor load
