### ISSUE TITLE
Simulation d'une resistance en sortie

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/pza-emu-hanmatek-hm310t#4]
Quand la psu est activé elle doit se comporter comme si une résistance de 100ohms était relié à la sortie

**Comment by QuentinChopinet** [comment]
La psu initialise une résistance de 100ohms. Cette résistance est stocké dans le registre 0x024 (registre laissé libre par la psu réelle). Cette résistance peut être modifiée par une requête Modbus 0x024.
