### ISSUE TITLE
Bad Product ID and Model ID ?

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/pza-emu-hanmatek-hm310t#6]
On the current emulator:
- Bus 001 Device 003: ID 2e8a:000a Hanmatek HM310T

but it should be 

- HM310T_USBID_VENDOR="1a86"
- HM310T_USBID_MODEL="7523"

**Comment by QuentinChopinet** [comment]
The product and vendor ID is correct on lsusb.
The "udevadm info --name /dev/serial/by-id/usb-<peripheric_data>" command is giving different value for real and for simulated PSU
