### ISSUE TITLE
The pico crash when sending power off

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/pza-emu-hanmatek-hm310t#7]
The pico stop responsing when sending Psu off command

**Comment by QuentinChopinet** [comment]
The Psu off command is 0x01 0x06 0x00 0x01 0x00 0x00 0xd8 0x0a. This command is well received by the Pico and interpreted.
The Pico response 0x01 0x06 0x00 0x01 0x00 0x00 0xd8 0x0d. The checksum (2 last byte) should be the same as the command. The Pico stdout (in text mode) translate every 0x0a to 0x0d 0x0a (line feed to carriage return + line feed). This translation is present wherever the 0x0a appear.
In the Psu off case, the checksum is wrong and there is a character that is dropped (the 0x0a added exceed the length of the Modbus frame).
The stdout binary mode avoid the lf (0x0a) to cr-lf (0x0d 0x0a) translation.
